### PR TITLE
Add APP_CNF_BDB_START_COMMISSIONING support

### PR DESCRIPTION
**Pull request by elvis-epx**
Add support for APP_CNF_BDB_START_COMMISSIONING

### CODE REVIEW

**Comment by simenkid** [comment]
@elvis-epx, I found the namespace would be APP_CONFIG in ZStack MT API documentation([SWRA198)](https://www.silabs.com/content/usergenerated/asi/cloud/attachments/siliconlabs/en/community/wireless/zigbee-and-thread/forum/jcr:content/content/primary/qna/etrx357-lr_cvs_texas-TmdR/Z-Stack%20Monitor%20and%20Test%20API.pdf), and you renamed it to DEBUG according to the [unpi convention](http://processors.wiki.ti.com/index.php/NPI_Type_SubSystem). I was wondering that using APP_CONFIG is more reasonable. How do you think?

**Comment by elvis-epx** [comment]
I'd prefer APP_CONFIG as well, but how is the best way to add this to unpi?

**Comment by simenkid** [comment]
cc-znp is based on the [unpi](https://github.com/simenkid/unpi/blob/master/index.js) module which has defined the subsys properly. Thus I prefer using APP_CONFIG in cc-znp as well.

**Comment by elvis-epx** [comment]
I'm not sure I follow, the code 15 is related to "RPC_SYS_DEBUG": 15
in unpi:master.

**Comment by simenkid** [comment]
Sorry, my mistake. I'd prefer using APP_CONFIG as well, but you are correct to follow the unpi to use "DEBUG" suffix as the namespace. After all, I think it would be better not to violate the unpi definition.
 
I'm going to merge your modification, thanks!

**Comment by elvis-epx** [comment]
Thanks, and big THANK YOU for your work in cc-znp!

**Pull request merged**
